version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lvlup-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
    name: lvlup-frontend-network
